name=SmartServoBridge
version=0.1.0
author=Nicholas Stedman <nick@robotstack.com>
maintainer=Nicholas Stedman <nick@robotstack.com>
sentence=A library for ESP32 that bridges between smart servos and web or serial clients.
paragraph=Allows control and monitoring of smart servos over a network connection using WebSockets or via direct serial port. Supports half-duplex UART communication and provides debug output.
category=Communication
url=https://github.com/robotstack/smart-servo-bridge
architectures=esp32
includes=SmartServoBridge.h
depends=WebSocketsServer